### ISSUE TITLE
Using run_ Lcecalib_ There is a line of code for qpep. m: load ('color_list. mat '); Can't find 'color'_ List. mat ',

### ISSUE THREAD

**Issue by wh-LEUNG** [HKUSTGZ-IADC/LCECalib#1]
Using run_ Lcecalib_ There is a line of code for qpep. m: load ('color_list. mat ');, Can't find 'color'_ List. mat ',

**Comment by kinggreat24** [comment]
> 

You can generate a color_list.mat yourself, such as 
![color_list](https://github.com/HKUSTGZ-IADC/LCECalib/assets/30688557/4a4f54d8-3089-46fa-9b8e-f93bcccf474a)

**Comment by gogojjh** [comment]
color_list is a Nx3 matrix, where each row store the RGB value, e.g., R([1 0 0]), G([0 1 0]), B([0 0 1]).

**Comment by wh-LEUNG** [comment]
get it! Thanks!
