### ISSUE TITLE
About the GT Extrinsic params of real_data RLFS01~03

### ISSUE THREAD

**Issue by kinggreat24** [HKUSTGZ-IADC/LCECalib#2]
Can tell me how to obtain the true value of the camera internal parameters and the true value of the camera and lidar external parameters? Thank you very much.

**Comment by gogojjh** [comment]
Please check the Section VI.A of our paper: ``https://arxiv.org/abs/2303.09825'': ``We then manually check and modify them. With 3-D–3-D point correspondences that are found, we can compute the “fake” ground truth with the iterative closest point (ICP) algorithm''.
Thanks.
